__all__ = ['SEQ_LEN', 'LSTM_UNITS', 'FEATURE_COLUMNS', 'TARGET_COLUMNS', 'BATCH_SIZE']

SEQ_LEN = 10
LSTM_UNITS = 64
FEATURE_COLUMNS = ['x', 'y', 'z']
TARGET_COLUMNS = ['x_sim', 'y_sim', 'z_sim']
BATCH_SIZE = 16